version: '3.3'

# See README.md for details.

services:
  # docker:
  #   image: docker:latest
  #   container_name: my-jenkins-docker

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-jenkins:latest
    container_name: my-jenkins
    environment:
      JENKINS_HOME: /data/jenkins
      DOCKER_HOST: tcp://host.docker.internal:2375
    ports:
        - 8080:8080
        - 8443:8443
        - 50000:50000
    # privileged: true
    restart: unless-stopped
    user: root
    volumes:
      - type: volume
        source: jenkins-data
        target: /data/jenkins

volumes:
  jenkins-data: